/**
 * Layout Component
 * Auto-generated by EHB-HOME Integrator
 */

import React from 'react';
import Link from 'next/link';
import Head from 'next/head';

export default function Layout({ children, title = 'EHB System' }) {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>{title} | EHB Enterprise System</title>
        <meta name="description" content="Enterprise Hybrid Blockchain System" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <Link href="/" className="flex items-center">
                <span className="text-xl font-bold text-gray-900">EHB</span>
                <span className="ml-1 text-sm text-blue-600">Enterprise</span>
              </Link>
            </div>
            
            <nav className="flex space-x-8">
              <Link href="/" className="text-gray-500 hover:text-gray-900 px-3 py-2 text-sm font-medium">
                Home
              </Link>
              <Link href="/status" className="text-gray-500 hover:text-gray-900 px-3 py-2 text-sm font-medium">
                Status
              </Link>
              <Link href="http://localhost:5000" target="_blank" rel="noopener noreferrer" className="text-gray-500 hover:text-gray-900 px-3 py-2 text-sm font-medium">
                Developer Portal
              </Link>
              <Link href="http://localhost:5006" target="_blank" rel="noopener noreferrer" className="text-gray-500 hover:text-gray-900 px-3 py-2 text-sm font-medium">
                Dashboard
              </Link>
            </nav>
          </div>
        </div>
      </header>
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {children}
      </main>
      
      <footer className="bg-white border-t border-gray-200 py-8 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="md:flex md:items-center md:justify-between">
            <div className="flex space-x-6 md:order-2">
              <Link href="http://localhost:5000/documentation" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-500">
                Documentation
              </Link>
              <Link href="http://localhost:5000/api" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-500">
                API
              </Link>
              <Link href="http://localhost:5000/support" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-500">
                Support
              </Link>
            </div>
            <div className="mt-8 md:mt-0 md:order-1">
              <p className="text-center text-base text-gray-400">
                &copy; 2025 Enterprise Hybrid Blockchain. All rights reserved.
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
