/**
 * ModuleCard Component
 * Auto-generated by EHB-HOME Integrator
 */

import React from 'react';
import Link from 'next/link';
import { checkModuleStatus } from '../utils/moduleScanner';

export default function ModuleCard({ module }) {
  const status = checkModuleStatus(module);
  
  return (
    <div className="bg-white rounded-lg shadow-md overflow-hidden transition-all transform hover:scale-105 hover:shadow-lg">
      <div className={`h-2 ${getStatusColor(status.status)}`}></div>
      <div className="p-5">
        <div className="flex justify-between items-start">
          <h3 className="text-xl font-bold text-gray-800">{module.name}</h3>
          <span className={`px-2 py-1 text-xs rounded-full ${getStatusBadgeColor(status.status)}`}>
            {status.status}
          </span>
        </div>
        
        <p className="text-gray-600 mt-2 text-sm">{module.description}</p>
        
        <div className="mt-4 pt-4 border-t border-gray-100 flex justify-between">
          <span className="text-xs text-gray-500 inline-flex items-center">
            <div className={`w-2 h-2 rounded-full ${getCategoryColor(module.type)} mr-1`}></div>
            {formatCategory(module.type)}
          </span>
          
          <div className="space-x-2">
            <Link href={module.url} target="_blank" rel="noopener noreferrer" 
              className="px-3 py-1 bg-blue-500 text-white text-xs rounded hover:bg-blue-600 transition-colors">
              Open
            </Link>
            
            <Link href={`/module/${module.id}`}
              className="px-3 py-1 bg-gray-200 text-gray-700 text-xs rounded hover:bg-gray-300 transition-colors">
              Details
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

function getStatusColor(status) {
  switch(status) {
    case 'online': return 'bg-green-500';
    case 'offline': return 'bg-red-500';
    case 'maintenance': return 'bg-yellow-500';
    case 'updating': return 'bg-blue-500';
    default: return 'bg-gray-500';
  }
}

function getStatusBadgeColor(status) {
  switch(status) {
    case 'online': return 'bg-green-100 text-green-800';
    case 'offline': return 'bg-red-100 text-red-800';
    case 'maintenance': return 'bg-yellow-100 text-yellow-800';
    case 'updating': return 'bg-blue-100 text-blue-800';
    default: return 'bg-gray-100 text-gray-800';
  }
}

function getCategoryColor(category) {
  switch(category) {
    case 'service': return 'bg-purple-500';
    case 'department': return 'bg-yellow-500';
    case 'admin': return 'bg-red-500';
    case 'affiliate': return 'bg-blue-500';
    case 'system': return 'bg-green-500';
    default: return 'bg-gray-500';
  }
}

function formatCategory(category) {
  return category.charAt(0).toUpperCase() + category.slice(1);
}
