/**
 * App Component
 * Auto-generated by EHB-HOME Integrator
 */

import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

export default MyApp;
