/**
 * Module Configuration
 * Auto-generated by EHB-HOME Integrator
 */

export const modules = [
  {
    "id": "ehb-home",
    "name": "EHB-HOME",
    "description": "The central dashboard and entry point for the entire EHB system.",
    "type": "system",
    "port": 5005,
    "url": "http://localhost:5005",
    "path": "/home/runner/workspace/EHB-HOME"
  }
];

export const MODULE_CATEGORIES = {
  SERVICE: 'service',
  DEPARTMENT: 'department',
  ADMIN: 'admin',
  AFFILIATE: 'affiliate',
  SYSTEM: 'system'
};
