/**
 * Module Scanner Utility
 * Auto-generated by EHB-HOME Integrator
 */

import { modules } from './moduleConfig';

export function getAllModules() {
  return modules;
}

export function getModulesByCategory(category) {
  return modules.filter(module => module.type === category);
}

export function getModuleById(id) {
  return modules.find(module => module.id === id);
}

export function getModuleByName(name) {
  return modules.find(module => module.name === name);
}

export function getServiceModules() {
  return getModulesByCategory('service');
}

export function getAdminModules() {
  return getModulesByCategory('admin');
}

export function getSystemModules() {
  return getModulesByCategory('system');
}

export function getDepartmentModules() {
  return getModulesByCategory('department');
}

export function getAffiliateModules() {
  return getModulesByCategory('affiliate');
}

export function checkModuleStatus(module) {
  // In a real implementation, this would check if the module is running
  // For now, we'll just return a placeholder status
  return { 
    status: 'online', 
    lastChecked: new Date().toISOString() 
  };
}
